# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: genesis.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rgenesis.proto\",\n\tReplyBase\x12\x0e\n\x06status\x18\x01 \x01(\x05\x12\x0f\n\x07message\x18\x02 \x01(\t\"&\n\x10RunScalerRequest\x12\x12\n\nscalerName\x18\x01 \x01(\t\",\n\x0eRunScalerReply\x12\x1a\n\x06status\x18\x01 \x01(\x0b\x32\n.ReplyBase2>\n\tGenesisRM\x12\x31\n\tRunScaler\x12\x11.RunScalerRequest\x1a\x0f.RunScalerReply\"\x00\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'genesis_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _REPLYBASE._serialized_start=17
  _REPLYBASE._serialized_end=61
  _RUNSCALERREQUEST._serialized_start=63
  _RUNSCALERREQUEST._serialized_end=101
  _RUNSCALERREPLY._serialized_start=103
  _RUNSCALERREPLY._serialized_end=147
  _GENESISRM._serialized_start=149
  _GENESISRM._serialized_end=211
# @@protoc_insertion_point(module_scope)
