# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import genesis_pb2 as genesis__pb2


class GenesisRMStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.RunScaler = channel.unary_unary(
                '/GenesisRM/RunScaler',
                request_serializer=genesis__pb2.RunScalerRequest.SerializeToString,
                response_deserializer=genesis__pb2.RunScalerReply.FromString,
                )


class GenesisRMServicer(object):
    """Missing associated documentation comment in .proto file."""

    def RunScaler(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_GenesisRMServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'RunScaler': grpc.unary_unary_rpc_method_handler(
                    servicer.RunScaler,
                    request_deserializer=genesis__pb2.RunScalerRequest.FromString,
                    response_serializer=genesis__pb2.RunScalerReply.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'GenesisRM', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class GenesisRM(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def RunScaler(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/GenesisRM/RunScaler',
            genesis__pb2.RunScalerRequest.SerializeToString,
            genesis__pb2.RunScalerReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
